server:
  port: 8988 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
#spring cloud注册:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: 
    keysecret: 
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: cole-edu-file
